### ISSUE TITLE
Issue 6 for Milestone 3 training the model

### ISSUE THREAD

**Issue by owokojr** [owokojr/Supply-chain-optimization#6]
-

- [x] [ ]Data splitting
- [x] -[ ]Bootsrapping
- [ ] -[ ]Cross validation(basic, repeated or LOOCV)
- [x] -[ ]Model training for either classification, regression, association or clustering.
- [x] -[ ]Model performance comparison using resamples (for classification and regression)
